<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Conheça os negócios do Conecta Bairros, veja detalhes e entre em contato.">
<title>Negócio local | Conecta Bairros</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#f3f4f6;color:#1e293b;font:16px/1.6 Segoe UI,Arial,sans-serif}header{background:#2563eb;color:white;padding:22px max(5%,calc((100vw - 1100px)/2))}header a{color:white;text-decoration:none;font-size:24px;font-weight:700}main{max-width:1100px;padding:24px;margin:auto}.voltar{display:inline-block;color:#1d4ed8;margin:0 0 24px}.layout{display:grid;grid-template-columns:1fr 1fr;gap:32px;background:white;border:1px solid #dbe4f1;border-radius:16px;padding:28px}.foto{width:100%;max-height:520px;object-fit:contain;background:#f8fafc;border-radius:12px}.sem-foto{padding:80px 20px;text-align:center;background:#eff6ff;border-radius:12px;color:#64748b}.categoria{color:#1d4ed8;font-size:13px;font-weight:700}h1{font-size:32px;line-height:1.2;overflow-wrap:anywhere;margin:10px 0 24px}h2{font-size:20px}#descricao{white-space:pre-wrap;overflow-wrap:anywhere}#endereco{overflow-wrap:anywhere}.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:20px}.button{display:inline-block;border:1px solid #cbd5e1;border-radius:8px;padding:12px 18px;font:inherit;cursor:pointer;background:white;color:#1e293b;text-decoration:none}.primary{background:#2563eb;color:white;border-color:#2563eb}.zap{background:#047857;color:white;border-color:#047857}.note{font-size:13px;color:#475569}#link-negocio{width:100%;padding:12px}a:focus-visible,button:focus-visible,input:focus-visible{outline:3px solid #2563eb;outline-offset:4px}[hidden]{display:none!important}footer{text-align:center;padding:30px;color:#64748b;font-size:13px}@media(max-width:700px){.layout{grid-template-columns:1fr;padding:18px;gap:20px}main{padding:18px}h1{font-size:28px}.actions{flex-direction:column}.button{text-align:center}}
</style>
</head>
<body><header><a href="index.php">Conecta Bairros 🏠</a></header>
<main><a class="voltar" href="index.php">← Voltar à busca de negócios</a><p id="status-pagina" role="status">Carregando informações do negócio…</p>
<article id="detalhe" class="layout" hidden><div><img id="foto" class="foto" alt="" hidden><div id="sem-foto" class="sem-foto">Foto ainda não disponível</div></div><div><span id="categoria" class="categoria"></span><h1 id="nome"></h1><h2>Sobre o negócio</h2><p id="descricao"></p><h2>Onde encontrar</h2><p id="endereco"></p><p id="aviso-rota" class="note"></p><p id="aviso-contato" class="note"></p><div class="actions"><a id="rota" class="button primary" target="_blank" rel="noopener noreferrer" hidden>Como chegar ↗</a><a id="whatsapp" class="button zap" target="_blank" rel="noopener noreferrer" hidden>Falar pelo WhatsApp ↗</a><button id="compartilhar" class="button" type="button">Copiar link do negócio</button></div><p id="status-compartilhar" class="note" role="status"></p><input id="link-negocio" aria-label="Link do negócio" readonly hidden></div></article></main>
<footer>Conecta Bairros · Valorizando o comércio local</footer>
<script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-app.js"></script><script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-firestore.js"></script><script src="assets/js/negocio-v1.js?v=1"></script></body></html>
